# Generated by Django 5.0.6 on 2024-05-11 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0010_faq_glossary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Glossary',
        ),
    ]
