# Generated by Django 5.0.6 on 2024-05-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0011_delete_glossary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Lab company', max_length=50)),
                ('description', models.TextField(default='This is a company')),
            ],
        ),
    ]
