# Generated by Django 5.1.1 on 2024-09-08 12:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0018_tag_news_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocode',
            options={},
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
