# Generated by Django 5.1.1 on 2024-09-08 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0021_glossary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Glossary',
        ),
    ]
