# Generated by Django 5.1.1 on 2024-09-15 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0023_prebook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prebook',
        ),
    ]
