# Generated by Django 5.1.1 on 2024-09-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0026_company_address_company_email_company_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='address',
        ),
        migrations.RemoveField(
            model_name='company',
            name='email',
        ),
        migrations.RemoveField(
            model_name='company',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='company',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='company',
            name='video',
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(default='This is a company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(default='Lab company', max_length=50),
        ),
    ]
