# Generated by Django 5.1.1 on 2024-10-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0027_remove_company_address_remove_company_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(default='This is a partner')),
                ('img', models.ImageField(blank=True, upload_to='partners')),
            ],
        ),
    ]
