# Generated by Django 5.1.1 on 2024-11-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0030_alter_contacts_description_alter_contacts_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='description',
            field=models.TextField(default='This is a contact'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.EmailField(default='defalt@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='img',
            field=models.ImageField(blank=True, upload_to='contacts'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phonenumber',
            field=models.CharField(max_length=15),
        ),
    ]
