# Generated by Django 5.1.1 on 2024-11-05 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0031_alter_contacts_description_alter_contacts_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='img',
            field=models.CharField(max_length=255),
        ),
    ]
