# Generated by Django 5.0.6 on 2024-05-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0008_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='country',
            field=models.CharField(default='us', max_length=50),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='state',
            field=models.CharField(default='ca', max_length=50),
        ),
    ]
