# Generated by Django 5.1.1 on 2024-09-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0019_alter_promocode_options_alter_promocode_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='summary',
            field=models.CharField(default='summary', max_length=255),
        ),
    ]
