# Generated by Django 5.1.1 on 2024-10-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0028_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
